name: CI/CD Workflow

on:
  push:
    branches:
    - coding

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Debug file structure
    - name: Debug file structure
      run: ls -R backend

    # Step 5: Run tests
    - name: Run tests
      run: |
        pytest  # Replace with your test framework

  create-pr:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/coding'

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Create Pull Request from coding to main
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: coding
        base: main
        title: "Automated PR: Merge coding into main"
        body: |
          This PR was automatically created by GitHub Actions.
          It merges changes from `coding` into `main`.
        commit-message: "Automated sync: Merge coding into main"

  auto-merge:
    needs: create-pr
    runs-on: ubuntu-latest

    steps:
    # Step 1: Automatically merge the PR if created
    - name: Merge Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { data: pullRequests } = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: "open",
            head: "coding",
          });
          if (pullRequests.length > 0) {
            const prNumber = pullRequests[0].number;
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: "squash",
            });
          }

  deploy:
    needs: auto-merge
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy application
    - name: Deploy application
      run: echo "Deploying to production" # Replace with your deployment script
