name: CI/CD Workflow

on:
  push:
    branches:
    - coding

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
        - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
          MYSQL_USER: ${{ secrets.DB_USER }}
          MYSQL_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Add .env Variables
    - name: Add .env Variables
      run: |
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

    # Step 4: Start MySQL Service
    - name: Start MySQL Service
      run: sudo systemctl start mysql

    # Step 5: Verify MySQL Service Status
    - name: Verify MySQL Service
      run: sudo systemctl status mysql

    # Step 6: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install spaCy model
      run: python -m spacy download en_core_web_sm

    # Step 7: Debug file structure
    - name: Debug file structure
      run: ls -R backend

    # Step 8: Test MySQL Connection
    - name: Test MySQL Connection
      run: |
        mysql -h 127.0.0.1 -u${{ secrets.DB_USER }} -p${{ secrets.DB_PASSWORD }} -e "SHOW DATABASES;"

    # Step 9: Run tests
    - name: Run tests
      run: pytest
